---
- name: add content and sync Sat 6.x
  hosts: sat
  become: yes

  vars_files: 
   - secrets.yml
#   - vars.yml

  vars:
    product: "Red Hat Enterprise Linux for x86_64"
#    repo_label: "satellite-tools-6.7-for-rhel-8-x86_64-rpms"
    repo_variants:
      - releasever: "7Server"
        basearch: "x86_64"
    organization: "Default Organization"

  tasks:
    - name: "enable sat tools 6.7 for rhel 8 repo"
      redhat.satellite.repository_set:
        label: satellite-tools-6.7-for-rhel-8-x86_64-rpms
        all_repositories: yes
        username: "admin"
        password: "{{ sat_password }}"
        server_url: "https://sat6.sdunne.aws"
        organization: "{{ organization }}"
        state: enabled

    - name: "enable rhel8 base rpms repos"
      redhat.satellite.repository_set:
        label: rhel-8-for-x86_64-baseos-rpms 
        repositories: 
          - releasever: "8.3"
        username: "admin"
        password: "{{ sat_password }}"
        server_url: "https://sat6.sdunne.aws"
        organization: "{{ organization }}"
        state: enabled

    - name: "enable rhel8 appstream rpms repos"
      redhat.satellite.repository_set:
        label: rhel-8-for-x86_64-appstream-rpms 
        repositories: 
          - releasever: "8.3"
        username: "admin"
        password: "{{ sat_password }}"
        server_url: "https://sat6.sdunne.aws"
        organization: "{{ organization }}"
        state: enabled

    - name: "sync repository"
      redhat.satellite.repository_sync:
        username: "admin"
        password: "{{ sat_password }}"
        server_url: "https://sat6.sdunne.aws"
        product: "{{ product }}"
        organization: "{{ organization }}"
      tags: never
 
