---
- name: provision ec2 instances
  hosts: localhost
  gather_facts: False
  become: false

  vars:
    instance_type: r5n.xlarge
    count: 1
    servername: sdunne-sat 
    iam_role: sdunne-sat6
    disk_size: 50

  tasks:
    - name: Provision ec2 instances
      ec2:
         key_name: "{{ keypair }}" 
         instance_type: "{{ instance_type }}" 
         image: "{{ sat_image }}"
         region: "{{ region }}" 
         group: "{{ group }}" 
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         count: "{{ count }}" 
         instance_tags:
           Name: "{{ servername }}"
           Owner: sdunne@redhat.com
#         instance_profile_name: "{{ iam_role }}"
         wait: yes
         volumes:
           - device_name: /dev/sda1
             volume_size: "{{ disk_size }}"
             delete_on_termination: yes
