---
- name: register with RHSM and other changes
  hosts: sat
  become: yes
  gather_facts: false

  vars_files: 
   - secrets.yml
#   - vars.yml

  vars:

  tasks:
    - name: remove aws rhui repos
      file:
        path: '{{ item }}'
        state: absent
      loop:
       - /etc/yum.repos.d/redhat-rhui-client-config.repo
       - /etc/yum.repos.d/redhat-rhui.repo
       - /etc/yum.repos.d/rhui-load-balancers.conf

    - name: change hostname
      hostname:
        name: "{{ sat_hostname }}"

    - name: subscription-manager register and attach pool
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}" 
        password: "{{ rhsm_password }}" 
        pool: "{{ sat_pool }}"

        #    - name: yum update all packages
        #yum:
        #name: "*"
        #state: latest

