---
- name: install Sat 6.x 
  hosts: sat
  become: yes

  vars_files: 
   - secrets.yml
#   - vars.yml

  vars:
    packages:
     - vim
     - tmux
     - insights-client
     - satellite

  tasks:
    - name: configure /etc/hosts for Sat requirement
      lineinfile:
        path: /etc/hosts
        insertafter: EOF
        line: "{{ ansible_facts.default_ipv4.address }} {{ sat_hostname }}"
      tags: hostsfile

    - name: Disable all RHSM repositories
      rhsm_repository:
        name: '*'
        state: disabled
      tags: never

    - name: enable repos for Satellite install
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      loop:
        - rhel-7-server-rpms
        - rhel-7-server-satellite-6.7-rpms
        - rhel-7-server-satellite-maintenance-6-rpms
        - rhel-server-rhscl-7-rpms 
        - rhel-7-server-ansible-2.8-rpms
      tags: never

    - name: install sat6 and other packages
      yum:
        name: "{{ packages }}"
        state: latest

    - name: yum update all packages
      yum:
        name: "*"
        state: latest

    - name: satellite-installer
      command: 'satellite-installer --scenario satellite --foreman-initial-admin-username admin --foreman-initial-admin-password "{{ sat_password }}" --foreman-proxy-puppetca true --foreman-proxy-tftp true --enable-foreman-plugin-discovery --enable-foreman-plugin-remote-execution-cockpit'
      register: sat_install_output

    - name: show sat install output
      debug:
        var: sat_install_output

    - name: register to insights
      insights_register:
        state: present
      tags: insights
