---
- name: register with RHSM and other changes
  hosts: tower
  become: yes
  gather_facts: false

  vars_files: 
   - secrets.yml
     #   - vars.yml

  vars:

  tasks:
    - name: remove aws rhui repos
      file:
        path: '{{ item }}'
        state: absent
      loop:
       - /etc/yum.repos.d/redhat-rhui-client-config.repo
       - /etc/yum.repos.d/redhat-rhui.repo
       - /etc/yum.repos.d/redhat-rhui-beta.repo.disabled

    - name: change hostname
      hostname:
        name: "{{ tower_hostname }}"

    - name: subscription-manager register and attach pool
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}" 
        password: "{{ rhsm_password }}" 
        pool: "{{ tower_pool }}"

    - name: yum update all packages
      yum:
        name: "*"
        state: latest

